spring:
  datasource:
    url: jdbc:h2:file:./data/inditex-app
    driver-class-name: org.h2.Driver
    username: user
    password: password
  jpa:
    ddl-auto: update
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
server:
  port: 8082

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG

