spring:
  datasource:
    url: jdbc:h2:file:./data/inditex-app
    driver-class-name: org.h2.Driver
    username: user
    password: password
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    ddl-auto: update
  h2:
    console:
      enabled: true
server:
  port: 8081