spring:
  datasource:
    url: jdbc:h2:file:./data/inditex-app
    driver-class-name: org.h2.Driver
    username: user
    password: password
  jpa:
    ddl-auto: update
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
server:
  port: 8082


