CREATE TABLE PRICES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    BRAND_ID INT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST INT NOT NULL,
    PRODUCT_ID VARCHAR(36) NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    CURR CHAR(3) NOT NULL
);
